# Change these first
owner: jaybinks # Your GitHub organization or username, where this repository lives
repo: test-uptime # The name of this repository

sites:
  - name: NetSIP Website
    url: https://www.netsip.com.au
  - name: NetSIP Customer Portal
    url: https://portal.overthewire.com.au/
  - name: SIP Cluster - 400har.nsw.sip.netsip.net.au TCP:5060
    check: "tcp-ping"
    url: 400har.nsw.sip.netsip.net.au	
    port: 5060
  - name: SIP Cluster - 47bou.nsw.sip.netsip.net.au TCP:5060
    check: "tcp-ping"
    url: 47bou.nsw.sip.netsip.net.au	
    port: 5060
  - name: SIP Cluster - 24lit.qld.sip.netsip.net.au TCP:5060
    check: "tcp-ping"
    url: 24lit.qld..sip.netsip.net.au	
    port: 5060
  - name: SIP Cluster - 100wic.qld.sip.netsip.net.au TCP:5060
    check: "tcp-ping"
    url: 100wic.qld..sip.netsip.net.au	
    port: 5060
  - name: SIP Cluster - 826lor.vic.sip.netsip.net.au TCP:5060
    check: "tcp-ping"
    url: 826lor.vic.sip.netsip.net.au	
    port: 5060
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  
  baseUrl: /test-uptime
  logoUrl: https://overthewire.com.au/wp-content/uploads/2021/04/netsip-logo.png
  #name: Upptime
  introTitle: "**NetSIP** service status"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: NetSIP 
      href: https://overthewire.com.au/netsip/
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
